global:
  scrape_interval: 5s # Як часто збирати дані

scrape_configs:
  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:3000"] # Внутрішня назва сервісу Docker

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:3001"] # порт для метрик
